libraries = [
    {
        "name": "NumPy",
        "description": "A fundamental package for numerical computing in Python, providing support for arrays, matrices, and mathematical functions.",
        "key_features": ["N-dimensional arrays", "Mathematical functions", "Linear algebra support"],
        "use_cases": ["Data analysis", "Scientific computing"],
        "latest_version": "1.25.0",
        "license": "BSD",
        "release_date": "2006-01-06",
        "repository": "https://github.com/numpy/numpy",
        "website": "https://numpy.org",
        "stars": 27700
    },
    {
        "name": "Pandas",
        "description": "A powerful data manipulation and analysis library, providing data structures like DataFrames for efficient data handling.",
        "key_features": ["DataFrame support", "Data manipulation", "Time series functionality"],
        "use_cases": ["Data analysis", "Data cleaning"],
        "latest_version": "2.0.3",
        "license": "BSD",
        "release_date": "2008-08-08",
        "repository": "https://github.com/pandas-dev/pandas",
        "website": "https://pandas.pydata.org",
        "stars": 43400
    },
    {
        "name": "Matplotlib",
        "description": "A plotting library for Python that enables the creation of static, animated, and interactive visualizations.",
        "key_features": ["2D plotting", "Integration with NumPy", "Wide range of plots"],
        "use_cases": ["Data visualization", "Scientific plotting"],
        "latest_version": "3.7.1",
        "license": "MATLAB",
        "release_date": "2003-01-01",
        "repository": "https://github.com/matplotlib/matplotlib",
        "website": "https://matplotlib.org",
        "stars": 21000
    },
    {
        "name": "Scikit-learn",
        "description": "A machine learning library that provides simple and efficient tools for data mining and data analysis.",
        "key_features": ["Classification", "Regression", "Clustering"],
        "use_cases": ["Machine learning", "Predictive modeling"],
        "latest_version": "1.2.0",
        "license": "BSD",
        "release_date": "2010-06-29",
        "repository": "https://github.com/scikit-learn/scikit-learn",
        "website": "https://scikit-learn.org",
        "stars": 59600
    },
    {
        "name": "TensorFlow",
        "description": "An end-to-end open-source platform for machine learning, including a comprehensive ecosystem of tools, libraries, and community resources.",
        "key_features": ["Deep learning", "Neural networks", "High-level APIs"],
        "use_cases": ["Deep learning", "Artificial intelligence"],
        "latest_version": "2.13.0",
        "license": "Apache 2.0",
        "release_date": "2015-11-09",
        "repository": "https://github.com/tensorflow/tensorflow",
        "website": "https://www.tensorflow.org",
        "stars": 186000
    },
    {
        "name": "Keras",
        "description": "A high-level neural networks API, written in Python, that runs on top of TensorFlow, enabling easy and fast experimentation.",
        "key_features": ["User-friendly", "Modular", "Extensible"],
        "use_cases": ["Deep learning", "Rapid prototyping"],
        "latest_version": "2.14.0",
        "license": "MIT",
        "release_date": "2015-03-27",
        "repository": "https://github.com/keras-team/keras",
        "website": "https://keras.io",
        "stars": 61700
    },
    {
        "name": "PyTorch",
        "description": "An open-source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing.",
        "key_features": ["Dynamic computation graph", "GPU support", "Rich ecosystem"],
        "use_cases": ["Deep learning", "Research"],
        "latest_version": "2.0.1",
        "license": "BSD",
        "release_date": "2016-09-24",
        "repository": "https://github.com/pytorch/pytorch",
        "website": "https://pytorch.org",
        "stars": 82600
    },
    {
        "name": "Statsmodels",
        "description": "A library for estimating and interpreting statistical models, including linear regression and time series analysis.",
        "key_features": ["Statistical models", "Hypothesis testing", "Data exploration"],
        "use_cases": ["Statistical analysis", "Econometrics"],
        "latest_version": "0.13.5",
        "license": "BSD",
        "release_date": "2010-05-01",
        "repository": "https://github.com/statsmodels/statsmodels",
        "website": "https://www.statsmodels.org",
        "stars": 10000
    },
    {
        "name": "Seaborn",
        "description": "A Python data visualization library based on Matplotlib, providing a high-level interface for drawing attractive statistical graphics.",
        "key_features": ["Statistical plots", "Color palettes", "Integration with Pandas"],
        "use_cases": ["Data visualization", "Exploratory data analysis"],
        "latest_version": "0.12.2",
        "license": "BSD",
        "release_date": "2013-01-01",
        "repository": "https://github.com/mwaskom/seaborn",
        "website": "https://seaborn.pydata.org",
        "stars": 12400
    },
    {
        "name": "NLTK",
        "description": "A platform for building Python programs to work with human language data, providing easy-to-use interfaces for over 50 corpora and lexical resources.",
        "key_features": ["Text processing", "Tokenization", "Stemming"],
        "use_cases": ["Natural language processing", "Text analysis"],
        "latest_version": "3.8.1",
        "license": "Apache 2.0",
        "release_date": "2001-04-05",
        "repository": "https://github.com/nltk/nltk",
        "website": "https://www.nltk.org",
        "stars": 13500
    },
    {
        "name": "spaCy",
        "description": "An open-source software library for advanced natural language processing in Python, designed specifically for production use.",
        "key_features": ["Fast and efficient", "Pre-trained models", "Named entity recognition"],
        "use_cases": ["Natural language processing", "Text classification"],
        "latest_version": "3.5.1",
        "license": "MIT",
        "release_date": "2016-10-20",
        "repository": "https://github.com/explosion/spaCy",
        "website": "https://spacy.io",
        "stars": 29800
    },
    {
        "name": "Gensim",
        "description": "A library for topic modeling and document similarity analysis, capable of handling large text corpora.",
        "key_features": ["Topic modeling", "Similarity queries", "Support for Word2Vec"],
        "use_cases": ["Natural language processing", "Text mining"],
        "latest_version": "4.2.0",
        "license": "GNU LGPL",
        "release_date": "2010-03-20",
        "repository": "https://github.com/RaRe-Technologies/gensim",
        "website": "https://radimrehurek.com/gensim/",
        "stars": 15600
    },
    {
        "name": "XGBoost",
        "description": "An optimized distributed gradient boosting library designed to be highly efficient, flexible, and portable.",
        "key_features": ["Gradient boosting", "Parallel processing", "Tree pruning"],
        "use_cases": ["Machine learning", "Predictive modeling"],
        "latest_version": "1.7.5",
        "license": "Apache 2.0",
        "release_date": "2016-06-03",
        "repository": "https://github.com/dmlc/xgboost",
        "website": "https://xgboost.readthedocs.io",
        "stars": 26100
    },
    {
        "name": "LightGBM",
        "description": "A gradient boosting framework that uses tree-based learning algorithms, designed for distributed and efficient training.",
        "key_features": ["Fast training", "Low memory usage", "Parallel learning"],
        "use_cases": ["Machine learning", "Large datasets"],
        "latest_version": "3.3.2",
        "license": "MIT",
        "release_date": "2017-03-29",
        "repository": "https://github.com/microsoft/LightGBM",
        "website": "https://lightgbm.readthedocs.io",
        "stars": 16600
    },
    {
        "name": "CatBoost",
        "description": "A gradient boosting library that handles categorical features automatically, offering state-of-the-art performance.",
        "key_features": ["Categorical feature support", "Fast training", "Robust to overfitting"],
        "use_cases": ["Machine learning", "Predictive modeling"],
        "latest_version": "1.1.0",
        "license": "Apache 2.0",
        "release_date": "2017-03-23",
        "repository": "https://github.com/catboost/catboost",
        "website": "https://catboost.ai",
        "stars": 8000
    },
    {
        "name": "OpenCV",
        "description": "An open-source computer vision and machine learning software library that provides a common infrastructure for computer vision applications.",
        "key_features": ["Image processing", "Computer vision", "Real-time applications"],
        "use_cases": ["Image recognition", "Video analysis"],
        "latest_version": "4.7.0",
        "license": "Apache 2.0",
        "release_date": "2000-10-17",
        "repository": "https://github.com/opencv/opencv",
        "website": "https://opencv.org",
        "stars": 78300
    },
    {
        "name": "Plotly",
        "description": "A graphing library that makes interactive, publication-quality graphs online.",
        "key_features": ["Interactive plots", "Dashboards", "Integration with web applications"],
        "use_cases": ["Data visualization", "Web applications"],
        "latest_version": "5.10.0",
        "license": "MIT",
        "release_date": "2015-06-01",
        "repository": "https://github.com/plotly/plotly.py",
        "website": "https://plotly.com/python/",
        "stars": 16100
    },
    {
        "name": "Bokeh",
        "description": "A powerful visualization library for Python that allows for interactive plots and dashboards.",
        "key_features": ["Interactive visualizations", "Web-based", "Large dataset handling"],
        "use_cases": ["Data visualization", "Interactive dashboards"],
        "latest_version": "2.4.3",
        "license": "BSD",
        "release_date": "2013-06-13",
        "repository": "https://github.com/bokeh/bokeh",
        "website": "https://bokeh.org",
        "stars": 19300
    },
    {
        "name": "PyCaret",
        "description": "An open-source, low-code machine learning library in Python that automates the machine learning workflow.",
        "key_features": ["End-to-end machine learning", "Comparative analysis", "Easy integration"],
        "use_cases": ["Machine learning", "Model evaluation"],
        "latest_version": "3.0.0",
        "license": "MIT",
        "release_date": "2020-05-01",
        "repository": "https://github.com/pycaret/pycaret",
        "website": "https://pycaret.org",
        "stars": 8900
    },
    {
        "name": "Dask",
        "description": "A flexible parallel computing library for analytics that integrates with existing Python libraries.",
        "key_features": ["Parallel computing", "Dataframe support", "Scalable"],
        "use_cases": ["Big data analysis", "Parallel processing"],
        "latest_version": "2023.9.1",
        "license": "BSD",
        "release_date": "2016-05-04",
        "repository": "https://github.com/dask/dask",
        "website": "https://dask.org",
        "stars": 12500
    },
    {
        "name": "MLflow",
        "description": "An open-source platform to manage the ML lifecycle, including experimentation, reproducibility, and deployment.",
        "key_features": ["Experiment tracking", "Model management", "Deployment"],
        "use_cases": ["Machine learning", "Model tracking"],
        "latest_version": "2.7.1",
        "license": "Apache 2.0",
        "release_date": "2018-06-19",
        "repository": "https://github.com/mlflow/mlflow",
        "website": "https://mlflow.org",
        "stars": 18400
    },
    {
        "name": "TPOT",
        "description": "A Python Automated Machine Learning tool that optimizes machine learning pipelines using genetic programming.",
        "key_features": ["Automated pipeline optimization", "Genetic programming", "Integration with scikit-learn"],
        "use_cases": ["Automated machine learning", "Model selection"],
        "latest_version": "1.6.0",
        "license": "MIT",
        "release_date": "2017-04-02",
        "repository": "https://github.com/EpistasisLab/tpot",
        "website": "http://epistasislab.github.io/tpot/",
        "stars": 9700
    }
]